language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm start > /dev/null &
- npm run update-webdriver
- sleep 1
script:
- node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  --browsers=Firefox
- node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
deploy:
  provider: heroku
  api-key:
    secure: Xl6FVKC9lief5Z2MVHS5MQFN4OykBogEZMAsXl1NmKUYAmjdsFxq40LPfogbS50pYIZXzk5lwg+wbExxLLu/cnTb4EYEswi+HIxU/23ly8QC395B1e+Q0blLyT52o8nR6bpBeqJ5DhMkToPHLYc0ymcx4SXPLELVJBpPlHPAsp7T7qsXlbdMILErrZVx9Epj/l6W62giWnvv4rgyl7KUevG/oqqvqPcZbQmLpXCEiXrzml2/SPJdQbqYHOVD+ohfNB87GPPg9aYcssW3/EqmZm/q/+MGUk6tmA3Mb/5fYjg0+vbfR6bAHqbrVcu4L/M6AnjLIgu8NTtOn2C61bnwzAfmqfRcaQo5Ev/7zT8WzvjItOACv85ljSZaHwSzvE14BR03T99oy5gWCN+3NEM78mPiHBdBXmhCSaMoszrYVb29L0RmmeIdQzaXWYMYeoIuNC26eY7a0mXkayAsQW3Y6bV1dPkoNN36IlLkiKjoXFgjyO59gA02ieIqVvnnQZdXnB4bDNKMN5XxdlTWIjQbex8361qAsySYHZC2EeBOg13sion5HlW93w1B6q2CWR5OXu1B/wnR+ZOQKOd2BJmGceBEkX0rmK3VrOIm9JcEuUTj+F87WwdR2ScTNn/dx2NJhEZ5J5N50Jww2TvmZlc4PWjqle+nk8VJ3jRaIb6ykkE=
  app: numericseriesapp
